import { createContext, useContext, useState, ReactNode } from 'react';

export type Language = 'en' | 'ru' | 'de' | 'es';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};

interface LanguageProviderProps {
  children: ReactNode;
}

export const LanguageProvider = ({ children }: LanguageProviderProps) => {
  const [language, setLanguage] = useState<Language>('en');

  const t = (key: string): string => {
    return translations[language][key] || translations.en[key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

const translations = {
  en: {
    // Navigation
    'nav.home': 'Home',
    'nav.roleProfile': 'Role Profile',
    'nav.skills': 'Skills',
    'nav.growthPlan': 'Growth Plan',
    'nav.progress': 'Progress',
    'nav.mentalModels': 'Mental Models',
    'nav.profile': 'Profile',

    // Home Page
    'home.title': 'Master Your Professional Growth',
    'home.subtitle': 'A personal development system that helps professionals articulate their role, assess growth areas, and follow a data-informed path toward mastery.',
    'home.getStarted': 'Get Started',
    'home.createProfile': 'Create your profile to begin your growth journey',
    'home.namePlaceholder': 'Your name',
    'home.emailPlaceholder': 'Your email',
    'home.startJourney': 'Start Your Journey',
    'home.creatingProfile': 'Creating Profile...',
    'home.tryAgain': 'Try Again',
    'home.missingInfo': 'Please enter both your name and email to get started.',
    'home.invalidEmail': 'Please enter a valid email address.',
    'home.profileCreated': 'Profile Created',
    'home.welcomeMessage': 'Welcome {name}! Let\'s set up your role profile.',
    'home.error': 'Failed to create your profile. Please try again.',

    // Features
    'feature.roleProfiler.title': 'Role Profiler',
    'feature.roleProfiler.description': 'AI-generated skill map based on your role and responsibilities',
    'feature.skillAssessment.title': 'Skill Assessment',
    'feature.skillAssessment.description': 'Self-assess your current abilities and identify growth areas',
    'feature.growthPlan.title': 'Growth Plan',
    'feature.growthPlan.description': 'Personalized recommendations for books, courses, and practices',
    'feature.mentalModels.title': 'Mental Models Coach',
    'feature.mentalModels.description': 'AI-powered decision support using proven mental frameworks',

    // Role Profile Page
    'roleProfile.title': 'Role Profiler',
    'roleProfile.subtitle': 'Describe your current job and responsibilities to generate a personalized skill map.',
    'roleProfile.describeRole': 'Describe Your Role',
    'roleProfile.beSpecific': 'Be specific about your responsibilities, the decisions you make, and the impact you have.',
    'roleProfile.placeholder': 'Example: I\'m a Product Manager at a SaaS company. I work with engineering teams to define product roadmaps, analyze user feedback, prioritize features, and coordinate launches. I also work closely with sales and marketing to understand market needs and communicate product value...',
    'roleProfile.generate': 'Generate Role Profile',
    'roleProfile.generating': 'Generating Profile...',
    'roleProfile.yourProfile': 'Your Role Profile',
    'roleProfile.archetype': 'AI-generated archetype:',
    'roleProfile.continue': 'Continue to Skill Assessment',
    'roleProfile.target': 'Target:',

    // Skill Assessment Page
    'skillAssessment.title': 'Skill Assessment',
    'skillAssessment.subtitle': 'Rate your current skill level (1-5) and provide examples of how you\'ve applied each skill.',
    'skillAssessment.currentLevel': 'Current Level (1-5)',
    'skillAssessment.examples': 'Examples of Application (Optional)',
    'skillAssessment.examplesPlaceholder': 'Describe specific examples of how you\'ve used this skill...',
    'skillAssessment.saveProgress': 'Save Progress',
    'skillAssessment.saving': 'Saving...',
    'skillAssessment.continue': 'Continue to Growth Plan',
    'skillAssessment.noProfile': 'No Role Profile Found',
    'skillAssessment.needProfile': 'You need to complete your role profile before you can assess your skills.',
    'skillAssessment.createProfile': 'Create Role Profile',
    'skillAssessment.saved': 'Assessment Saved',
    'skillAssessment.savedMessage': 'Your skill assessments have been saved successfully.',

    // Growth Plan Page
    'growthPlan.title': 'Growth Plan',
    'growthPlan.subtitle': 'AI-generated recommendations based on your skill gaps and development goals.',
    'growthPlan.generate': 'Generate Your Growth Plan',
    'growthPlan.generateDescription': 'Based on your skill assessment, we\'ll create a personalized development plan.',
    'growthPlan.generateButton': 'Generate Growth Plan',
    'growthPlan.generating': 'Generating Plan...',
    'growthPlan.recommendations': 'Your Recommendations',
    'growthPlan.regenerate': 'Regenerate Plan',
    'growthPlan.regenerating': 'Regenerating...',
    'growthPlan.continue': 'Continue to Progress Tracker',
    'growthPlan.books': 'Books',
    'growthPlan.courses': 'Courses',
    'growthPlan.habits': 'Habits',
    'growthPlan.missions': 'Missions',
    'growthPlan.pending': 'Pending',
    'growthPlan.inProgress': 'In Progress',
    'growthPlan.done': 'Done',
    'growthPlan.generated': 'Growth Plan Generated',
    'growthPlan.generatedMessage': 'Generated {count} personalized recommendations.',
    'growthPlan.noGaps': 'No Gaps Found',
    'growthPlan.noGapsMessage': 'You\'re already at your target levels! Consider setting higher goals.',
    'growthPlan.statusUpdated': 'Status Updated',
    'growthPlan.statusUpdatedMessage': 'Item marked as {status}.',

    // Progress Tracker Page
    'progress.title': 'Progress Tracker',
    'progress.subtitle': 'Track your development journey and reflect on your learnings.',
    'progress.overallProgress': 'Overall Progress',
    'progress.completedItems': 'Completed Items',
    'progress.skillGaps': 'Skill Gaps',
    'progress.averageProgress': 'Average skill development progress',
    'progress.outOfTotal': 'out of {total} total items',
    'progress.areasForImprovement': 'areas for improvement',
    'progress.skillsByArea': 'Skill Progress by Area',
    'progress.skillsRated': 'all skills rated 1-5',
    'progress.current': 'Current:',
    'progress.target': 'Target:',
    'progress.skillsNeedingImprovement': 'Skills Needing Improvement',
    'progress.focusAreas': 'Focus areas where you haven\'t reached your target level yet',
    'progress.gap': 'Gap:',
    'progress.level': 'level',
    'progress.levels': 'levels',
    'progress.reflectionJournal': 'Reflection Journal',
    'progress.documentLearnings': 'Document your learnings, insights, and progress',
    'progress.reflectionPlaceholder': 'What have you learned recently? What challenges are you facing? What insights have you gained?',
    'progress.saveReflection': 'Save Reflection',
    'progress.saving': 'Saving...',
    'progress.recentReflections': 'Recent Reflections',
    'progress.moreReflections': 'And {count} more reflections...',
    'progress.reflectionSaved': 'Reflection Saved',
    'progress.reflectionSavedMessage': 'Your reflection has been added to your journal.',

    // Mental Models Page
    'mentalModels.title': 'Mental Models Coach',
    'mentalModels.subtitle': 'Get AI-powered insights using proven mental frameworks to help with complex decisions and dilemmas.',
    'mentalModels.describeSituation': 'Describe Your Situation',
    'mentalModels.shareDecision': 'Share a decision you\'re facing, a challenge you\'re working through, or a situation you\'d like to analyze from multiple perspectives.',
    'mentalModels.placeholder': 'Example: I\'m trying to decide whether to take on a new project that would stretch my team thin but could lead to significant growth opportunities. The timeline is aggressive and there\'s risk of burnout, but the potential impact is high...',
    'mentalModels.analyze': 'Analyze with Mental Models',
    'mentalModels.analyzing': 'Analyzing...',
    'mentalModels.yourSituation': 'Your Situation',
    'mentalModels.analysis': 'Mental Model Analysis',
    'mentalModels.saveToJournal': 'Save to Journal',
    'mentalModels.newAnalysis': 'New Analysis',
    'mentalModels.explanation': 'Explanation',
    'mentalModels.newPerspective': 'New Perspective',
    'mentalModels.keyInsight': 'Key Insight',
    'mentalModels.practicalAction': 'Practical Action',
    'mentalModels.analysisComplete': 'Analysis Complete',
    'mentalModels.analysisCompleteMessage': 'Generated {count} mental model perspectives on your situation.',
    'mentalModels.savedToJournal': 'Saved to Journal',
    'mentalModels.savedToJournalMessage': 'Mental model analysis has been saved to your reflection journal.',

    // Profile Page
    'profile.title': 'Profile',
    'profile.subtitle': 'Manage your professional development profile and track your progress.',
    'profile.overview': 'Overview',
    'profile.roleProfile': 'Role Profile',
    'profile.skills': 'Skills',
    'profile.settings': 'Settings',
    'profile.memberSince': 'Member since',
    'profile.currentRole': 'Current Role',
    'profile.yourStrengths': 'Your Strengths',
    'profile.strengthsDescription': 'Skills where you\'ve reached or exceeded your target level',
    'profile.recentGrowthActivities': 'Recent Growth Activities',
    'profile.recentActivitiesDescription': 'Your latest development activities and their status',
    'profile.moreItems': 'And {count} more items...',
    'profile.roleArchetype': 'Role Archetype',
    'profile.aiGeneratedProfile': 'AI-generated professional profile',
    'profile.regenerate': 'Regenerate',
    'profile.skillMap': 'Skill Map',
    'profile.skillMapDescription': 'Comprehensive breakdown of skills required for your role',
    'profile.noRoleProfile': 'No Role Profile',
    'profile.noRoleProfileDescription': 'You haven\'t created a role profile yet. Generate one to get started.',
    'profile.createRoleProfile': 'Create Role Profile',
    'profile.noSkillsAssessed': 'No Skills Assessed',
    'profile.noSkillsDescription': 'Complete your skill assessment to see your progress here.',
    'profile.startSkillAssessment': 'Start Skill Assessment',
    'profile.profileInformation': 'Profile Information',
    'profile.updateInformation': 'Update your personal information and role description',
    'profile.edit': 'Edit',
    'profile.name': 'Name',
    'profile.email': 'Email',
    'profile.emailCannotChange': 'Email cannot be changed',
    'profile.roleDescription': 'Role Description',
    'profile.noRoleDescription': 'No role description provided',
    'profile.saveChanges': 'Save Changes',
    'profile.cancel': 'Cancel',
    'profile.accountInformation': 'Account Information',
    'profile.accountDetails': 'Your account details and membership information',
    'profile.lastUpdated': 'Last Updated',
    'profile.skillsAssessed': 'Skills Assessed',
    'profile.growthItems': 'Growth Items',
    'profile.dataManagement': 'Data Management',
    'profile.manageData': 'Manage your profile data and regenerate content',
    'profile.regenerateRoleProfile': 'Regenerate Role Profile',
    'profile.updateSkillAssessment': 'Update Skill Assessment',
    'profile.regenerateGrowthPlan': 'Regenerate Growth Plan',
    'profile.atTargetLevel': 'at target level',

    // Common
    'common.loading': 'Loading...',
    'common.error': 'Error',
    'common.save': 'Save',
    'common.cancel': 'Cancel',
    'common.continue': 'Continue',
    'common.back': 'Back',
    'common.next': 'Next',
    'common.previous': 'Previous',
    'common.close': 'Close',
    'common.delete': 'Delete',
    'common.edit': 'Edit',
    'common.view': 'View',
    'common.add': 'Add',
    'common.remove': 'Remove',
    'common.update': 'Update',
    'common.create': 'Create',
    'common.generate': 'Generate',
    'common.regenerate': 'Regenerate',
    'common.analyze': 'Analyze',
    'common.tryAgain': 'Try Again',
    'common.goHome': 'Go Home',
    'common.notFound': 'Not found',
    'common.success': 'Success',
    'common.warning': 'Warning',
    'common.info': 'Info',
  },
  ru: {
    // Navigation
    'nav.home': 'Главная',
    'nav.roleProfile': 'Профиль роли',
    'nav.skills': 'Навыки',
    'nav.growthPlan': 'План развития',
    'nav.progress': 'Прогресс',
    'nav.mentalModels': 'Ментальные модели',
    'nav.profile': 'Профиль',

    // Home Page
    'home.title': 'Освойте свой профессиональный рост',
    'home.subtitle': 'Система личного развития, которая помогает профессионалам сформулировать свою роль, оценить области роста и следовать информированному пути к мастерству.',
    'home.getStarted': 'Начать',
    'home.createProfile': 'Создайте свой профиль, чтобы начать путь развития',
    'home.namePlaceholder': 'Ваше имя',
    'home.emailPlaceholder': 'Ваш email',
    'home.startJourney': 'Начать путешествие',
    'home.creatingProfile': 'Создание профиля...',
    'home.tryAgain': 'Попробовать снова',
    'home.missingInfo': 'Пожалуйста, введите ваше имя и email для начала.',
    'home.invalidEmail': 'Пожалуйста, введите действительный email адрес.',
    'home.profileCreated': 'Профиль создан',
    'home.welcomeMessage': 'Добро пожаловать, {name}! Давайте настроим ваш профиль роли.',
    'home.error': 'Не удалось создать ваш профиль. Пожалуйста, попробуйте снова.',

    // Features
    'feature.roleProfiler.title': 'Профайлер роли',
    'feature.roleProfiler.description': 'ИИ-генерированная карта навыков на основе вашей роли и обязанностей',
    'feature.skillAssessment.title': 'Оценка навыков',
    'feature.skillAssessment.description': 'Самооценка ваших текущих способностей и выявление областей роста',
    'feature.growthPlan.title': 'План развития',
    'feature.growthPlan.description': 'Персонализированные рекомендации по книгам, курсам и практикам',
    'feature.mentalModels.title': 'Коуч ментальных моделей',
    'feature.mentalModels.description': 'ИИ-поддержка принятия решений с использованием проверенных ментальных фреймворков',

    // Role Profile Page
    'roleProfile.title': 'Профайлер роли',
    'roleProfile.subtitle': 'Опишите вашу текущую работу и обязанности для создания персонализированной карты навыков.',
    'roleProfile.describeRole': 'Опишите вашу роль',
    'roleProfile.beSpecific': 'Будьте конкретны в отношении ваших обязанностей, решений, которые вы принимаете, и влияния, которое вы оказываете.',
    'roleProfile.placeholder': 'Пример: Я продакт-менеджер в SaaS компании. Я работаю с командами разработки для определения дорожных карт продуктов, анализирую отзывы пользователей, расставляю приоритеты функций и координирую запуски. Я также тесно работаю с отделами продаж и маркетинга для понимания потребностей рынка и коммуникации ценности продукта...',
    'roleProfile.generate': 'Создать профиль роли',
    'roleProfile.generating': 'Создание профиля...',
    'roleProfile.yourProfile': 'Ваш профиль роли',
    'roleProfile.archetype': 'ИИ-генерированный архетип:',
    'roleProfile.continue': 'Перейти к оценке навыков',
    'roleProfile.target': 'Цель:',

    // Skill Assessment Page
    'skillAssessment.title': 'Оценка навыков',
    'skillAssessment.subtitle': 'Оцените ваш текущий уровень навыков (1-5) и приведите примеры применения каждого навыка.',
    'skillAssessment.currentLevel': 'Текущий уровень (1-5)',
    'skillAssessment.examples': 'Примеры применения (необязательно)',
    'skillAssessment.examplesPlaceholder': 'Опишите конкретные примеры использования этого навыка...',
    'skillAssessment.saveProgress': 'Сохранить прогресс',
    'skillAssessment.saving': 'Сохранение...',
    'skillAssessment.continue': 'Перейти к плану развития',
    'skillAssessment.noProfile': 'Профиль роли не найден',
    'skillAssessment.needProfile': 'Вам нужно завершить профиль роли перед оценкой навыков.',
    'skillAssessment.createProfile': 'Создать профиль роли',
    'skillAssessment.saved': 'Оценка сохранена',
    'skillAssessment.savedMessage': 'Ваши оценки навыков успешно сохранены.',

    // Growth Plan Page
    'growthPlan.title': 'План развития',
    'growthPlan.subtitle': 'ИИ-генерированные рекомендации на основе ваших пробелов в навыках и целей развития.',
    'growthPlan.generate': 'Создать ваш план развития',
    'growthPlan.generateDescription': 'На основе вашей оценки навыков мы создадим персонализированный план развития.',
    'growthPlan.generateButton': 'Создать план развития',
    'growthPlan.generating': 'Создание плана...',
    'growthPlan.recommendations': 'Ваши рекомендации',
    'growthPlan.regenerate': 'Пересоздать план',
    'growthPlan.regenerating': 'Пересоздание...',
    'growthPlan.continue': 'Перейти к отслеживанию прогресса',
    'growthPlan.books': 'Книги',
    'growthPlan.courses': 'Курсы',
    'growthPlan.habits': 'Привычки',
    'growthPlan.missions': 'Миссии',
    'growthPlan.pending': 'В ожидании',
    'growthPlan.inProgress': 'В процессе',
    'growthPlan.done': 'Выполнено',
    'growthPlan.generated': 'План развития создан',
    'growthPlan.generatedMessage': 'Создано {count} персонализированных рекомендаций.',
    'growthPlan.noGaps': 'Пробелы не найдены',
    'growthPlan.noGapsMessage': 'Вы уже на целевых уровнях! Рассмотрите возможность установки более высоких целей.',
    'growthPlan.statusUpdated': 'Статус обновлен',
    'growthPlan.statusUpdatedMessage': 'Элемент отмечен как {status}.',

    // Progress Tracker Page
    'progress.title': 'Отслеживание прогресса',
    'progress.subtitle': 'Отслеживайте ваш путь развития и размышляйте о ваших достижениях.',
    'progress.overallProgress': 'Общий прогресс',
    'progress.completedItems': 'Завершенные элементы',
    'progress.skillGaps': 'Пробелы в навыках',
    'progress.averageProgress': 'Средний прогресс развития навыков',
    'progress.outOfTotal': 'из {total} общих элементов',
    'progress.areasForImprovement': 'области для улучшения',
    'progress.skillsByArea': 'Прогресс навыков по областям',
    'progress.skillsRated': 'все навыки оценены по шкале 1-5',
    'progress.current': 'Текущий:',
    'progress.target': 'Цель:',
    'progress.skillsNeedingImprovement': 'Навыки, требующие улучшения',
    'progress.focusAreas': 'Области фокуса, где вы еще не достигли целевого уровня',
    'progress.gap': 'Пробел:',
    'progress.level': 'уровень',
    'progress.levels': 'уровней',
    'progress.reflectionJournal': 'Журнал размышлений',
    'progress.documentLearnings': 'Документируйте ваши знания, инсайты и прогресс',
    'progress.reflectionPlaceholder': 'Что вы недавно изучили? С какими вызовами сталкиваетесь? Какие инсайты получили?',
    'progress.saveReflection': 'Сохранить размышление',
    'progress.saving': 'Сохранение...',
    'progress.recentReflections': 'Недавние размышления',
    'progress.moreReflections': 'И еще {count} размышлений...',
    'progress.reflectionSaved': 'Размышление сохранено',
    'progress.reflectionSavedMessage': 'Ваше размышление добавлено в журнал.',

    // Mental Models Page
    'mentalModels.title': 'Коуч ментальных моделей',
    'mentalModels.subtitle': 'Получите ИИ-инсайты, используя проверенные ментальные фреймворки для помощи в сложных решениях и дилеммах.',
    'mentalModels.describeSituation': 'Опишите вашу ситуацию',
    'mentalModels.shareDecision': 'Поделитесь решением, которое вы принимаете, вызовом, над которым работаете, или ситуацией, которую хотите проанализировать с разных точек зрения.',
    'mentalModels.placeholder': 'Пример: Я пытаюсь решить, стоит ли браться за новый проект, который растянет мою команду, но может привести к значительным возможностям роста. График агрессивный и есть риск выгорания, но потенциальное влияние высокое...',
    'mentalModels.analyze': 'Анализировать с ментальными моделями',
    'mentalModels.analyzing': 'Анализ...',
    'mentalModels.yourSituation': 'Ваша ситуация',
    'mentalModels.analysis': 'Анализ ментальных моделей',
    'mentalModels.saveToJournal': 'Сохранить в журнал',
    'mentalModels.newAnalysis': 'Новый анализ',
    'mentalModels.explanation': 'Объяснение',
    'mentalModels.newPerspective': 'Новая перспектива',
    'mentalModels.keyInsight': 'Ключевой инсайт',
    'mentalModels.practicalAction': 'Практическое действие',
    'mentalModels.analysisComplete': 'Анализ завершен',
    'mentalModels.analysisCompleteMessage': 'Создано {count} перспектив ментальных моделей для вашей ситуации.',
    'mentalModels.savedToJournal': 'Сохранено в журнал',
    'mentalModels.savedToJournalMessage': 'Анализ ментальных моделей сохранен в ваш журнал размышлений.',

    // Profile Page
    'profile.title': 'Профиль',
    'profile.subtitle': 'Управляйте вашим профилем профессионального развития и отслеживайте прогресс.',
    'profile.overview': 'Обзор',
    'profile.roleProfile': 'Профиль роли',
    'profile.skills': 'Навыки',
    'profile.settings': 'Настройки',
    'profile.memberSince': 'Участник с',
    'profile.currentRole': 'Текущая роль',
    'profile.yourStrengths': 'Ваши сильные стороны',
    'profile.strengthsDescription': 'Навыки, где вы достигли или превысили целевой уровень',
    'profile.recentGrowthActivities': 'Недавние активности развития',
    'profile.recentActivitiesDescription': 'Ваши последние активности развития и их статус',
    'profile.moreItems': 'И еще {count} элементов...',
    'profile.roleArchetype': 'Архетип роли',
    'profile.aiGeneratedProfile': 'ИИ-генерированный профессиональный профиль',
    'profile.regenerate': 'Пересоздать',
    'profile.skillMap': 'Карта навыков',
    'profile.skillMapDescription': 'Комплексная разбивка навыков, необходимых для вашей роли',
    'profile.noRoleProfile': 'Нет профиля роли',
    'profile.noRoleProfileDescription': 'Вы еще не создали профиль роли. Создайте его для начала.',
    'profile.createRoleProfile': 'Создать профиль роли',
    'profile.noSkillsAssessed': 'Навыки не оценены',
    'profile.noSkillsDescription': 'Завершите оценку навыков, чтобы увидеть прогресс здесь.',
    'profile.startSkillAssessment': 'Начать оценку навыков',
    'profile.profileInformation': 'Информация профиля',
    'profile.updateInformation': 'Обновите вашу личную информацию и описание роли',
    'profile.edit': 'Редактировать',
    'profile.name': 'Имя',
    'profile.email': 'Email',
    'profile.emailCannotChange': 'Email нельзя изменить',
    'profile.roleDescription': 'Описание роли',
    'profile.noRoleDescription': 'Описание роли не предоставлено',
    'profile.saveChanges': 'Сохранить изменения',
    'profile.cancel': 'Отмена',
    'profile.accountInformation': 'Информация аккаунта',
    'profile.accountDetails': 'Детали вашего аккаунта и информация о членстве',
    'profile.lastUpdated': 'Последнее обновление',
    'profile.skillsAssessed': 'Оценено навыков',
    'profile.growthItems': 'Элементы развития',
    'profile.dataManagement': 'Управление данными',
    'profile.manageData': 'Управляйте данными профиля и пересоздавайте контент',
    'profile.regenerateRoleProfile': 'Пересоздать профиль роли',
    'profile.updateSkillAssessment': 'Обновить оценку навыков',
    'profile.regenerateGrowthPlan': 'Пересоздать план развития',
    'profile.atTargetLevel': 'на целевом уровне',

    // Common
    'common.loading': 'Загрузка...',
    'common.error': 'Ошибка',
    'common.save': 'Сохранить',
    'common.cancel': 'Отмена',
    'common.continue': 'Продолжить',
    'common.back': 'Назад',
    'common.next': 'Далее',
    'common.previous': 'Предыдущий',
    'common.close': 'Закрыть',
    'common.delete': 'Удалить',
    'common.edit': 'Редактировать',
    'common.view': 'Просмотр',
    'common.add': 'Добавить',
    'common.remove': 'Удалить',
    'common.update': 'Обновить',
    'common.create': 'Создать',
    'common.generate': 'Создать',
    'common.regenerate': 'Пересоздать',
    'common.analyze': 'Анализировать',
    'common.tryAgain': 'Попробовать снова',
    'common.goHome': 'На главную',
    'common.notFound': 'Не найдено',
    'common.success': 'Успех',
    'common.warning': 'Предупреждение',
    'common.info': 'Информация',
  },
  de: {
    // Navigation
    'nav.home': 'Startseite',
    'nav.roleProfile': 'Rollenprofil',
    'nav.skills': 'Fähigkeiten',
    'nav.growthPlan': 'Entwicklungsplan',
    'nav.progress': 'Fortschritt',
    'nav.mentalModels': 'Mentale Modelle',
    'nav.profile': 'Profil',

    // Home Page
    'home.title': 'Meistern Sie Ihr berufliches Wachstum',
    'home.subtitle': 'Ein System zur persönlichen Entwicklung, das Fachkräften hilft, ihre Rolle zu artikulieren, Wachstumsbereiche zu bewerten und einem datengestützten Weg zur Meisterschaft zu folgen.',
    'home.getStarted': 'Loslegen',
    'home.createProfile': 'Erstellen Sie Ihr Profil, um Ihre Wachstumsreise zu beginnen',
    'home.namePlaceholder': 'Ihr Name',
    'home.emailPlaceholder': 'Ihre E-Mail',
    'home.startJourney': 'Reise beginnen',
    'home.creatingProfile': 'Profil wird erstellt...',
    'home.tryAgain': 'Erneut versuchen',
    'home.missingInfo': 'Bitte geben Sie sowohl Ihren Namen als auch Ihre E-Mail ein, um zu beginnen.',
    'home.invalidEmail': 'Bitte geben Sie eine gültige E-Mail-Adresse ein.',
    'home.profileCreated': 'Profil erstellt',
    'home.welcomeMessage': 'Willkommen {name}! Lassen Sie uns Ihr Rollenprofil einrichten.',
    'home.error': 'Ihr Profil konnte nicht erstellt werden. Bitte versuchen Sie es erneut.',

    // Features
    'feature.roleProfiler.title': 'Rollen-Profiler',
    'feature.roleProfiler.description': 'KI-generierte Fähigkeitskarte basierend auf Ihrer Rolle und Verantwortlichkeiten',
    'feature.skillAssessment.title': 'Fähigkeitsbewertung',
    'feature.skillAssessment.description': 'Bewerten Sie Ihre aktuellen Fähigkeiten selbst und identifizieren Sie Wachstumsbereiche',
    'feature.growthPlan.title': 'Entwicklungsplan',
    'feature.growthPlan.description': 'Personalisierte Empfehlungen für Bücher, Kurse und Praktiken',
    'feature.mentalModels.title': 'Mentale Modelle Coach',
    'feature.mentalModels.description': 'KI-gestützte Entscheidungshilfe mit bewährten mentalen Frameworks',

    // Role Profile Page
    'roleProfile.title': 'Rollen-Profiler',
    'roleProfile.subtitle': 'Beschreiben Sie Ihren aktuellen Job und Ihre Verantwortlichkeiten, um eine personalisierte Fähigkeitskarte zu erstellen.',
    'roleProfile.describeRole': 'Beschreiben Sie Ihre Rolle',
    'roleProfile.beSpecific': 'Seien Sie spezifisch über Ihre Verantwortlichkeiten, die Entscheidungen, die Sie treffen, und den Einfluss, den Sie haben.',
    'roleProfile.placeholder': 'Beispiel: Ich bin Produktmanager in einem SaaS-Unternehmen. Ich arbeite mit Entwicklungsteams zusammen, um Produkt-Roadmaps zu definieren, Nutzerfeedback zu analysieren, Features zu priorisieren und Launches zu koordinieren. Ich arbeite auch eng mit Vertrieb und Marketing zusammen, um Marktbedürfnisse zu verstehen und Produktwert zu kommunizieren...',
    'roleProfile.generate': 'Rollenprofil erstellen',
    'roleProfile.generating': 'Profil wird erstellt...',
    'roleProfile.yourProfile': 'Ihr Rollenprofil',
    'roleProfile.archetype': 'KI-generierter Archetyp:',
    'roleProfile.continue': 'Weiter zur Fähigkeitsbewertung',
    'roleProfile.target': 'Ziel:',

    // Skill Assessment Page
    'skillAssessment.title': 'Fähigkeitsbewertung',
    'skillAssessment.subtitle': 'Bewerten Sie Ihr aktuelles Fähigkeitsniveau (1-5) und geben Sie Beispiele dafür an, wie Sie jede Fähigkeit angewendet haben.',
    'skillAssessment.currentLevel': 'Aktuelles Niveau (1-5)',
    'skillAssessment.examples': 'Anwendungsbeispiele (Optional)',
    'skillAssessment.examplesPlaceholder': 'Beschreiben Sie spezifische Beispiele, wie Sie diese Fähigkeit eingesetzt haben...',
    'skillAssessment.saveProgress': 'Fortschritt speichern',
    'skillAssessment.saving': 'Speichern...',
    'skillAssessment.continue': 'Weiter zum Entwicklungsplan',
    'skillAssessment.noProfile': 'Kein Rollenprofil gefunden',
    'skillAssessment.needProfile': 'Sie müssen Ihr Rollenprofil vervollständigen, bevor Sie Ihre Fähigkeiten bewerten können.',
    'skillAssessment.createProfile': 'Rollenprofil erstellen',
    'skillAssessment.saved': 'Bewertung gespeichert',
    'skillAssessment.savedMessage': 'Ihre Fähigkeitsbewertungen wurden erfolgreich gespeichert.',

    // Growth Plan Page
    'growthPlan.title': 'Entwicklungsplan',
    'growthPlan.subtitle': 'KI-generierte Empfehlungen basierend auf Ihren Fähigkeitslücken und Entwicklungszielen.',
    'growthPlan.generate': 'Erstellen Sie Ihren Entwicklungsplan',
    'growthPlan.generateDescription': 'Basierend auf Ihrer Fähigkeitsbewertung erstellen wir einen personalisierten Entwicklungsplan.',
    'growthPlan.generateButton': 'Entwicklungsplan erstellen',
    'growthPlan.generating': 'Plan wird erstellt...',
    'growthPlan.recommendations': 'Ihre Empfehlungen',
    'growthPlan.regenerate': 'Plan neu erstellen',
    'growthPlan.regenerating': 'Neu erstellen...',
    'growthPlan.continue': 'Weiter zum Fortschritts-Tracker',
    'growthPlan.books': 'Bücher',
    'growthPlan.courses': 'Kurse',
    'growthPlan.habits': 'Gewohnheiten',
    'growthPlan.missions': 'Missionen',
    'growthPlan.pending': 'Ausstehend',
    'growthPlan.inProgress': 'In Bearbeitung',
    'growthPlan.done': 'Erledigt',
    'growthPlan.generated': 'Entwicklungsplan erstellt',
    'growthPlan.generatedMessage': '{count} personalisierte Empfehlungen erstellt.',
    'growthPlan.noGaps': 'Keine Lücken gefunden',
    'growthPlan.noGapsMessage': 'Sie sind bereits auf Ihren Zielniveaus! Erwägen Sie höhere Ziele zu setzen.',
    'growthPlan.statusUpdated': 'Status aktualisiert',
    'growthPlan.statusUpdatedMessage': 'Element als {status} markiert.',

    // Progress Tracker Page
    'progress.title': 'Fortschritts-Tracker',
    'progress.subtitle': 'Verfolgen Sie Ihre Entwicklungsreise und reflektieren Sie über Ihre Lernerfahrungen.',
    'progress.overallProgress': 'Gesamtfortschritt',
    'progress.completedItems': 'Abgeschlossene Elemente',
    'progress.skillGaps': 'Fähigkeitslücken',
    'progress.averageProgress': 'Durchschnittlicher Fähigkeitsentwicklungsfortschritt',
    'progress.outOfTotal': 'von {total} Gesamtelementen',
    'progress.areasForImprovement': 'Verbesserungsbereiche',
    'progress.skillsByArea': 'Fähigkeitsfortschritt nach Bereichen',
    'progress.skillsRated': 'alle Fähigkeiten bewertet 1-5',
    'progress.current': 'Aktuell:',
    'progress.target': 'Ziel:',
    'progress.skillsNeedingImprovement': 'Fähigkeiten, die Verbesserung benötigen',
    'progress.focusAreas': 'Fokusbereich, wo Sie Ihr Zielniveau noch nicht erreicht haben',
    'progress.gap': 'Lücke:',
    'progress.level': 'Niveau',
    'progress.levels': 'Niveaus',
    'progress.reflectionJournal': 'Reflexionsjournal',
    'progress.documentLearnings': 'Dokumentieren Sie Ihre Lernerfahrungen, Einsichten und Fortschritte',
    'progress.reflectionPlaceholder': 'Was haben Sie kürzlich gelernt? Welchen Herausforderungen stehen Sie gegenüber? Welche Einsichten haben Sie gewonnen?',
    'progress.saveReflection': 'Reflexion speichern',
    'progress.saving': 'Speichern...',
    'progress.recentReflections': 'Aktuelle Reflexionen',
    'progress.moreReflections': 'Und {count} weitere Reflexionen...',
    'progress.reflectionSaved': 'Reflexion gespeichert',
    'progress.reflectionSavedMessage': 'Ihre Reflexion wurde zu Ihrem Journal hinzugefügt.',

    // Mental Models Page
    'mentalModels.title': 'Mentale Modelle Coach',
    'mentalModels.subtitle': 'Erhalten Sie KI-gestützte Einsichten mit bewährten mentalen Frameworks zur Hilfe bei komplexen Entscheidungen und Dilemmata.',
    'mentalModels.describeSituation': 'Beschreiben Sie Ihre Situation',
    'mentalModels.shareDecision': 'Teilen Sie eine Entscheidung mit, vor der Sie stehen, eine Herausforderung, an der Sie arbeiten, oder eine Situation, die Sie aus mehreren Perspektiven analysieren möchten.',
    'mentalModels.placeholder': 'Beispiel: Ich versuche zu entscheiden, ob ich ein neues Projekt übernehmen soll, das mein Team dünn strecken würde, aber zu erheblichen Wachstumschancen führen könnte. Der Zeitplan ist aggressiv und es besteht Burnout-Risiko, aber die potenzielle Wirkung ist hoch...',
    'mentalModels.analyze': 'Mit mentalen Modellen analysieren',
    'mentalModels.analyzing': 'Analysieren...',
    'mentalModels.yourSituation': 'Ihre Situation',
    'mentalModels.analysis': 'Mentale Modelle Analyse',
    'mentalModels.saveToJournal': 'Im Journal speichern',
    'mentalModels.newAnalysis': 'Neue Analyse',
    'mentalModels.explanation': 'Erklärung',
    'mentalModels.newPerspective': 'Neue Perspektive',
    'mentalModels.keyInsight': 'Schlüsseleinsicht',
    'mentalModels.practicalAction': 'Praktische Aktion',
    'mentalModels.analysisComplete': 'Analyse abgeschlossen',
    'mentalModels.analysisCompleteMessage': '{count} mentale Modell-Perspektiven für Ihre Situation erstellt.',
    'mentalModels.savedToJournal': 'Im Journal gespeichert',
    'mentalModels.savedToJournalMessage': 'Mentale Modelle Analyse wurde in Ihrem Reflexionsjournal gespeichert.',

    // Profile Page
    'profile.title': 'Profil',
    'profile.subtitle': 'Verwalten Sie Ihr berufliches Entwicklungsprofil und verfolgen Sie Ihren Fortschritt.',
    'profile.overview': 'Übersicht',
    'profile.roleProfile': 'Rollenprofil',
    'profile.skills': 'Fähigkeiten',
    'profile.settings': 'Einstellungen',
    'profile.memberSince': 'Mitglied seit',
    'profile.currentRole': 'Aktuelle Rolle',
    'profile.yourStrengths': 'Ihre Stärken',
    'profile.strengthsDescription': 'Fähigkeiten, wo Sie Ihr Zielniveau erreicht oder übertroffen haben',
    'profile.recentGrowthActivities': 'Aktuelle Wachstumsaktivitäten',
    'profile.recentActivitiesDescription': 'Ihre neuesten Entwicklungsaktivitäten und deren Status',
    'profile.moreItems': 'Und {count} weitere Elemente...',
    'profile.roleArchetype': 'Rollen-Archetyp',
    'profile.aiGeneratedProfile': 'KI-generiertes Berufsprofil',
    'profile.regenerate': 'Neu erstellen',
    'profile.skillMap': 'Fähigkeitskarte',
    'profile.skillMapDescription': 'Umfassende Aufschlüsselung der für Ihre Rolle erforderlichen Fähigkeiten',
    'profile.noRoleProfile': 'Kein Rollenprofil',
    'profile.noRoleProfileDescription': 'Sie haben noch kein Rollenprofil erstellt. Erstellen Sie eines, um zu beginnen.',
    'profile.createRoleProfile': 'Rollenprofil erstellen',
    'profile.noSkillsAssessed': 'Keine Fähigkeiten bewertet',
    'profile.noSkillsDescription': 'Vervollständigen Sie Ihre Fähigkeitsbewertung, um hier Fortschritte zu sehen.',
    'profile.startSkillAssessment': 'Fähigkeitsbewertung starten',
    'profile.profileInformation': 'Profilinformationen',
    'profile.updateInformation': 'Aktualisieren Sie Ihre persönlichen Informationen und Rollenbeschreibung',
    'profile.edit': 'Bearbeiten',
    'profile.name': 'Name',
    'profile.email': 'E-Mail',
    'profile.emailCannotChange': 'E-Mail kann nicht geändert werden',
    'profile.roleDescription': 'Rollenbeschreibung',
    'profile.noRoleDescription': 'Keine Rollenbeschreibung angegeben',
    'profile.saveChanges': 'Änderungen speichern',
    'profile.cancel': 'Abbrechen',
    'profile.accountInformation': 'Kontoinformationen',
    'profile.accountDetails': 'Ihre Kontodetails und Mitgliedschaftsinformationen',
    'profile.lastUpdated': 'Zuletzt aktualisiert',
    'profile.skillsAssessed': 'Bewertete Fähigkeiten',
    'profile.growthItems': 'Wachstumselemente',
    'profile.dataManagement': 'Datenverwaltung',
    'profile.manageData': 'Verwalten Sie Ihre Profildaten und erstellen Sie Inhalte neu',
    'profile.regenerateRoleProfile': 'Rollenprofil neu erstellen',
    'profile.updateSkillAssessment': 'Fähigkeitsbewertung aktualisieren',
    'profile.regenerateGrowthPlan': 'Entwicklungsplan neu erstellen',
    'profile.atTargetLevel': 'auf Zielniveau',

    // Common
    'common.loading': 'Laden...',
    'common.error': 'Fehler',
    'common.save': 'Speichern',
    'common.cancel': 'Abbrechen',
    'common.continue': 'Weiter',
    'common.back': 'Zurück',
    'common.next': 'Weiter',
    'common.previous': 'Vorherige',
    'common.close': 'Schließen',
    'common.delete': 'Löschen',
    'common.edit': 'Bearbeiten',
    'common.view': 'Ansehen',
    'common.add': 'Hinzufügen',
    'common.remove': 'Entfernen',
    'common.update': 'Aktualisieren',
    'common.create': 'Erstellen',
    'common.generate': 'Erstellen',
    'common.regenerate': 'Neu erstellen',
    'common.analyze': 'Analysieren',
    'common.tryAgain': 'Erneut versuchen',
    'common.goHome': 'Zur Startseite',
    'common.notFound': 'Nicht gefunden',
    'common.success': 'Erfolg',
    'common.warning': 'Warnung',
    'common.info': 'Info',
  },
  es: {
    // Navigation
    'nav.home': 'Inicio',
    'nav.roleProfile': 'Perfil de Rol',
    'nav.skills': 'Habilidades',
    'nav.growthPlan': 'Plan de Crecimiento',
    'nav.progress': 'Progreso',
    'nav.mentalModels': 'Modelos Mentales',
    'nav.profile': 'Perfil',

    // Home Page
    'home.title': 'Domina tu Crecimiento Profesional',
    'home.subtitle': 'Un sistema de desarrollo personal que ayuda a los profesionales a articular su rol, evaluar áreas de crecimiento y seguir un camino informado hacia la maestría.',
    'home.getStarted': 'Comenzar',
    'home.createProfile': 'Crea tu perfil para comenzar tu viaje de crecimiento',
    'home.namePlaceholder': 'Tu nombre',
    'home.emailPlaceholder': 'Tu email',
    'home.startJourney': 'Comenzar Viaje',
    'home.creatingProfile': 'Creando Perfil...',
    'home.tryAgain': 'Intentar de Nuevo',
    'home.missingInfo': 'Por favor ingresa tanto tu nombre como tu email para comenzar.',
    'home.invalidEmail': 'Por favor ingresa una dirección de email válida.',
    'home.profileCreated': 'Perfil Creado',
    'home.welcomeMessage': '¡Bienvenido {name}! Configuremos tu perfil de rol.',
    'home.error': 'No se pudo crear tu perfil. Por favor intenta de nuevo.',

    // Features
    'feature.roleProfiler.title': 'Perfilador de Rol',
    'feature.roleProfiler.description': 'Mapa de habilidades generado por IA basado en tu rol y responsabilidades',
    'feature.skillAssessment.title': 'Evaluación de Habilidades',
    'feature.skillAssessment.description': 'Autoevalúa tus habilidades actuales e identifica áreas de crecimiento',
    'feature.growthPlan.title': 'Plan de Crecimiento',
    'feature.growthPlan.description': 'Recomendaciones personalizadas para libros, cursos y prácticas',
    'feature.mentalModels.title': 'Coach de Modelos Mentales',
    'feature.mentalModels.description': 'Soporte de decisiones impulsado por IA usando marcos mentales probados',

    // Role Profile Page
    'roleProfile.title': 'Perfilador de Rol',
    'roleProfile.subtitle': 'Describe tu trabajo actual y responsabilidades para generar un mapa de habilidades personalizado.',
    'roleProfile.describeRole': 'Describe tu Rol',
    'roleProfile.beSpecific': 'Sé específico sobre tus responsabilidades, las decisiones que tomas y el impacto que tienes.',
    'roleProfile.placeholder': 'Ejemplo: Soy un Gerente de Producto en una empresa SaaS. Trabajo con equipos de ingeniería para definir hojas de ruta de productos, analizar comentarios de usuarios, priorizar características y coordinar lanzamientos. También trabajo estrechamente con ventas y marketing para entender las necesidades del mercado y comunicar el valor del producto...',
    'roleProfile.generate': 'Generar Perfil de Rol',
    'roleProfile.generating': 'Generando Perfil...',
    'roleProfile.yourProfile': 'Tu Perfil de Rol',
    'roleProfile.archetype': 'Arquetipo generado por IA:',
    'roleProfile.continue': 'Continuar a Evaluación de Habilidades',
    'roleProfile.target': 'Objetivo:',

    // Skill Assessment Page
    'skillAssessment.title': 'Evaluación de Habilidades',
    'skillAssessment.subtitle': 'Califica tu nivel actual de habilidades (1-5) y proporciona ejemplos de cómo has aplicado cada habilidad.',
    'skillAssessment.currentLevel': 'Nivel Actual (1-5)',
    'skillAssessment.examples': 'Ejemplos de Aplicación (Opcional)',
    'skillAssessment.examplesPlaceholder': 'Describe ejemplos específicos de cómo has usado esta habilidad...',
    'skillAssessment.saveProgress': 'Guardar Progreso',
    'skillAssessment.saving': 'Guardando...',
    'skillAssessment.continue': 'Continuar al Plan de Crecimiento',
    'skillAssessment.noProfile': 'No se Encontró Perfil de Rol',
    'skillAssessment.needProfile': 'Necesitas completar tu perfil de rol antes de poder evaluar tus habilidades.',
    'skillAssessment.createProfile': 'Crear Perfil de Rol',
    'skillAssessment.saved': 'Evaluación Guardada',
    'skillAssessment.savedMessage': 'Tus evaluaciones de habilidades se han guardado exitosamente.',

    // Growth Plan Page
    'growthPlan.title': 'Plan de Crecimiento',
    'growthPlan.subtitle': 'Recomendaciones generadas por IA basadas en tus brechas de habilidades y objetivos de desarrollo.',
    'growthPlan.generate': 'Genera tu Plan de Crecimiento',
    'growthPlan.generateDescription': 'Basado en tu evaluación de habilidades, crearemos un plan de desarrollo personalizado.',
    'growthPlan.generateButton': 'Generar Plan de Crecimiento',
    'growthPlan.generating': 'Generando Plan...',
    'growthPlan.recommendations': 'Tus Recomendaciones',
    'growthPlan.regenerate': 'Regenerar Plan',
    'growthPlan.regenerating': 'Regenerando...',
    'growthPlan.continue': 'Continuar al Rastreador de Progreso',
    'growthPlan.books': 'Libros',
    'growthPlan.courses': 'Cursos',
    'growthPlan.habits': 'Hábitos',
    'growthPlan.missions': 'Misiones',
    'growthPlan.pending': 'Pendiente',
    'growthPlan.inProgress': 'En Progreso',
    'growthPlan.done': 'Completado',
    'growthPlan.generated': 'Plan de Crecimiento Generado',
    'growthPlan.generatedMessage': 'Se generaron {count} recomendaciones personalizadas.',
    'growthPlan.noGaps': 'No se Encontraron Brechas',
    'growthPlan.noGapsMessage': '¡Ya estás en tus niveles objetivo! Considera establecer metas más altas.',
    'growthPlan.statusUpdated': 'Estado Actualizado',
    'growthPlan.statusUpdatedMessage': 'Elemento marcado como {status}.',

    // Progress Tracker Page
    'progress.title': 'Rastreador de Progreso',
    'progress.subtitle': 'Rastrea tu viaje de desarrollo y reflexiona sobre tus aprendizajes.',
    'progress.overallProgress': 'Progreso General',
    'progress.completedItems': 'Elementos Completados',
    'progress.skillGaps': 'Brechas de Habilidades',
    'progress.averageProgress': 'Progreso promedio de desarrollo de habilidades',
    'progress.outOfTotal': 'de {total} elementos totales',
    'progress.areasForImprovement': 'áreas para mejora',
    'progress.skillsByArea': 'Progreso de Habilidades por Área',
    'progress.skillsRated': 'todas las habilidades calificadas 1-5',
    'progress.current': 'Actual:',
    'progress.target': 'Objetivo:',
    'progress.skillsNeedingImprovement': 'Habilidades que Necesitan Mejora',
    'progress.focusAreas': 'Áreas de enfoque donde aún no has alcanzado tu nivel objetivo',
    'progress.gap': 'Brecha:',
    'progress.level': 'nivel',
    'progress.levels': 'niveles',
    'progress.reflectionJournal': 'Diario de Reflexión',
    'progress.documentLearnings': 'Documenta tus aprendizajes, perspicacias y progreso',
    'progress.reflectionPlaceholder': '¿Qué has aprendido recientemente? ¿Qué desafíos estás enfrentando? ¿Qué perspicacias has obtenido?',
    'progress.saveReflection': 'Guardar Reflexión',
    'progress.saving': 'Guardando...',
    'progress.recentReflections': 'Reflexiones Recientes',
    'progress.moreReflections': 'Y {count} reflexiones más...',
    'progress.reflectionSaved': 'Reflexión Guardada',
    'progress.reflectionSavedMessage': 'Tu reflexión ha sido añadida a tu diario.',

    // Mental Models Page
    'mentalModels.title': 'Coach de Modelos Mentales',
    'mentalModels.subtitle': 'Obtén perspicacias impulsadas por IA usando marcos mentales probados para ayudar con decisiones complejas y dilemas.',
    'mentalModels.describeSituation': 'Describe tu Situación',
    'mentalModels.shareDecision': 'Comparte una decisión que estés enfrentando, un desafío en el que estés trabajando, o una situación que te gustaría analizar desde múltiples perspectivas.',
    'mentalModels.placeholder': 'Ejemplo: Estoy tratando de decidir si tomar un nuevo proyecto que estiraría a mi equipo pero podría llevar a oportunidades de crecimiento significativas. El cronograma es agresivo y hay riesgo de agotamiento, pero el impacto potencial es alto...',
    'mentalModels.analyze': 'Analizar con Modelos Mentales',
    'mentalModels.analyzing': 'Analizando...',
    'mentalModels.yourSituation': 'Tu Situación',
    'mentalModels.analysis': 'Análisis de Modelos Mentales',
    'mentalModels.saveToJournal': 'Guardar en Diario',
    'mentalModels.newAnalysis': 'Nuevo Análisis',
    'mentalModels.explanation': 'Explicación',
    'mentalModels.newPerspective': 'Nueva Perspectiva',
    'mentalModels.keyInsight': 'Perspicacia Clave',
    'mentalModels.practicalAction': 'Acción Práctica',
    'mentalModels.analysisComplete': 'Análisis Completo',
    'mentalModels.analysisCompleteMessage': 'Se generaron {count} perspectivas de modelos mentales sobre tu situación.',
    'mentalModels.savedToJournal': 'Guardado en Diario',
    'mentalModels.savedToJournalMessage': 'El análisis de modelos mentales se ha guardado en tu diario de reflexión.',

    // Profile Page
    'profile.title': 'Perfil',
    'profile.subtitle': 'Gestiona tu perfil de desarrollo profesional y rastrea tu progreso.',
    'profile.overview': 'Resumen',
    'profile.roleProfile': 'Perfil de Rol',
    'profile.skills': 'Habilidades',
    'profile.settings': 'Configuración',
    'profile.memberSince': 'Miembro desde',
    'profile.currentRole': 'Rol Actual',
    'profile.yourStrengths': 'Tus Fortalezas',
    'profile.strengthsDescription': 'Habilidades donde has alcanzado o superado tu nivel objetivo',
    'profile.recentGrowthActivities': 'Actividades de Crecimiento Recientes',
    'profile.recentActivitiesDescription': 'Tus últimas actividades de desarrollo y su estado',
    'profile.moreItems': 'Y {count} elementos más...',
    'profile.roleArchetype': 'Arquetipo de Rol',
    'profile.aiGeneratedProfile': 'Perfil profesional generado por IA',
    'profile.regenerate': 'Regenerar',
    'profile.skillMap': 'Mapa de Habilidades',
    'profile.skillMapDescription': 'Desglose completo de habilidades requeridas para tu rol',
    'profile.noRoleProfile': 'Sin Perfil de Rol',
    'profile.noRoleProfileDescription': 'Aún no has creado un perfil de rol. Genera uno para comenzar.',
    'profile.createRoleProfile': 'Crear Perfil de Rol',
    'profile.noSkillsAssessed': 'Sin Habilidades Evaluadas',
    'profile.noSkillsDescription': 'Completa tu evaluación de habilidades para ver el progreso aquí.',
    'profile.startSkillAssessment': 'Comenzar Evaluación de Habilidades',
    'profile.profileInformation': 'Información del Perfil',
    'profile.updateInformation': 'Actualiza tu información personal y descripción del rol',
    'profile.edit': 'Editar',
    'profile.name': 'Nombre',
    'profile.email': 'Email',
    'profile.emailCannotChange': 'El email no se puede cambiar',
    'profile.roleDescription': 'Descripción del Rol',
    'profile.noRoleDescription': 'No se proporcionó descripción del rol',
    'profile.saveChanges': 'Guardar Cambios',
    'profile.cancel': 'Cancelar',
    'profile.accountInformation': 'Información de la Cuenta',
    'profile.accountDetails': 'Los detalles de tu cuenta e información de membresía',
    'profile.lastUpdated': 'Última Actualización',
    'profile.skillsAssessed': 'Habilidades Evaluadas',
    'profile.growthItems': 'Elementos de Crecimiento',
    'profile.dataManagement': 'Gestión de Datos',
    'profile.manageData': 'Gestiona los datos de tu perfil y regenera contenido',
    'profile.regenerateRoleProfile': 'Regenerar Perfil de Rol',
    'profile.updateSkillAssessment': 'Actualizar Evaluación de Habilidades',
    'profile.regenerateGrowthPlan': 'Regenerar Plan de Crecimiento',
    'profile.atTargetLevel': 'en nivel objetivo',

    // Common
    'common.loading': 'Cargando...',
    'common.error': 'Error',
    'common.save': 'Guardar',
    'common.cancel': 'Cancelar',
    'common.continue': 'Continuar',
    'common.back': 'Atrás',
    'common.next': 'Siguiente',
    'common.previous': 'Anterior',
    'common.close': 'Cerrar',
    'common.delete': 'Eliminar',
    'common.edit': 'Editar',
    'common.view': 'Ver',
    'common.add': 'Añadir',
    'common.remove': 'Remover',
    'common.update': 'Actualizar',
    'common.create': 'Crear',
    'common.generate': 'Generar',
    'common.regenerate': 'Regenerar',
    'common.analyze': 'Analizar',
    'common.tryAgain': 'Intentar de Nuevo',
    'common.goHome': 'Ir al Inicio',
    'common.notFound': 'No encontrado',
    'common.success': 'Éxito',
    'common.warning': 'Advertencia',
    'common.info': 'Información',
  }
};
